name: Release Action

on:
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read version
        id: version
        run: |
          pip3 install semver
          python3 scripts/release.py

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release v${{ steps.version.outputs.version }}
          prerelease: ${{ steps.version.outputs.prerelease }}
          generate_release_notes: true

      - name: Cargo publish
        run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }} --allow-dirty --no-verify
